### ISSUE TITLE
Customize Copy Widget in Code Block

### ISSUE THREAD

**Issue by cliftonlabrum** [chenzhiguang/markdown_viewer#59]
Is it possible to customize the icon used for copying the text in a code block?

As is, the icon won't adapt to my app changing to dark mode, so I'd like to control that by passing in a widget, if possible. 😄

<img width="374" alt="code-block" src="https://user-images.githubusercontent.com/2513753/202834762-aab36895-7019-4e2a-b5f1-0ffd83c9d31e.png">

**Comment by chenzhiguang** [comment]
Thanks! 
Sure, I will add it later today.

**Comment by chenzhiguang** [comment]
Fixed, it will be released next week by Tuesday.

**Comment by cliftonlabrum** [comment]
Fantastic, thank you!

Just curious, does Google review all commits to a Pub.dev package?

**Comment by chenzhiguang** [comment]
Nope, except the Google official packages.

**Comment by chenzhiguang** [comment]
@cliftonlabrum 

Hi, just let you know I have added a `copyIconColor` option for `MarkdownStyle` (PR: https://github.com/tagnote-app/markdown_viewer/pull/73), so you do not have to build the copy icon widget if you only want to change the copy icon color.

Also I have updated the default styles for dark mode, it look a bit better now.

Please update to `markdown_viewer: ^0.4.10` if you want to.

**Comment by cliftonlabrum** [comment]
Excellent, thank you!
