### ISSUE TITLE
Feature Request: Generate Plain Text from Markdown String

### ISSUE THREAD

**Issue by cliftonlabrum** [chenzhiguang/markdown_viewer#60]
Sometimes you need a plain text version of your Markdown syntax like when showing preview text like this:

<img width="699" alt="markdown-preview" src="https://user-images.githubusercontent.com/2513753/202834840-7e2a320b-cbf2-4c09-ab3e-571a6a843f5b.png">

See how the Markdown characters show up in the item on the left? It would be nice to just have plain text for that.

A workaround would be to create a style-less Markdown rendering to display in a preview, but that seems like overkill. 😅

Thank you!

**Comment by chenzhiguang** [comment]
Here is the solution:

```dart
const text = 'This is text, **bold**, and _italic_, ~~delete~~, and more.';

final nodes = Markdown().parse(text);
final plainText = nodes.map((e) => e.textContent).join();

print(plainText);
```

**Comment by cliftonlabrum** [comment]
Thanks for your quick reply!

Interesting... where is `Markdown()` from? Is that a separate package I need to add to my project?

**Comment by chenzhiguang** [comment]
Ah, sorry, I did not realise that, here it is: https://pub.dev/packages/dart_markdown

It is a dependency of the markdown_viewer.

**Comment by cliftonlabrum** [comment]
Ah, perfect. Thank you very much!
