### ISSUE TITLE
Flutter 3.7.3 Conflicts on DesktopTextSelectionToolbar

### ISSUE THREAD

**Issue by cliftonlabrum** [chenzhiguang/markdown_viewer#77]
After upgrading to `Flutter 3.7.3`, I am getting this error:

> Error (Xcode): ../../.pub-cache/hosted/pub.dev/markdown_viewer-0.4.10/lib/src/selection/markdown_selection_controls.dart:33:14: Error: 'DesktopTextSelectionToolbar' is imported from both 'package:flutter/src/material/desktop_text_selection_toolbar.dart' and 'package:markdown_viewer/src/selection/desktop_text_selection_toolbar.dart'.

It seems that there's a conflict between the `DesktopTextSelectionToolbar` found in the `MarkdownSelectionControls` and a class that Material has.

I just wanted to confirm if you also see this error when building a project with `markdown_viewer` in it, or if it's just me and my setup. 😆

Thanks!

**Comment by chenzhiguang** [comment]
Hi @cliftonlabrum, I think it is an issue of this package. I will fix it asap.

**Comment by chenzhiguang** [comment]
Fixed, please update to `markdown_viewer 0.5.0` and try again.

**Comment by cliftonlabrum** [comment]
It works! 🥳 Thank you! 😊
