### ISSUE TITLE
Table are not scrollable

### ISSUE THREAD

**Issue by ari-borlaza** [chenzhiguang/markdown_viewer#80]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/77093746/236473831-7d469be6-88ee-43e6-9c71-c2362389bb4f.png">

how can i fix the table to make it a scrolllable one because it is being cropped otherwise

**Comment by chenzhiguang** [comment]
Thanks for reporting this issue, I will fix it

**Comment by ari-borlaza** [comment]
thank you

**Comment by chenzhiguang** [comment]
@ari-borlaza  Fixed, please update to `markdown_viewer: ^0.6.0`

**Comment by ari-borlaza** [comment]
Thank you very much! This fixes it!

**Comment by JCKodel** [comment]
Don't know if this created the issue but, tables are not 100% width when they don't scroll.

Tables should occupy the whole width area, then scroll. Such as this:

| Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column |
| Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column |
| Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column |


| Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column |
| Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column |
| Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column | Very large column |

If this is too hard to implement, maybe there should be an extra setting for us to tell the render if we want or not a scrolling table.

**Comment by chenzhiguang** [comment]
@JCKodel maybe we should have an extra setting to force the tables to occupy the whole width, what do you think?

**Comment by JCKodel** [comment]
I think: if you want a table, then build a `Table` widget =)

Markdown should be simple, and the scroll should be the exception.

**Comment by chenzhiguang** [comment]
The table is a `Table` widget:

https://github.com/tagnote-app/markdown_viewer/blob/master/lib/src/builders/table_bilder.dart#L104

**Comment by JCKodel** [comment]
> The table is a `Table` widget:
> 
> https://github.com/tagnote-app/markdown_viewer/blob/master/lib/src/builders/table_bilder.dart#L104

I know =)

What I meant was: if one needs a real Table with scroll and everything, they should go for a Table widget, not trying to make it on markdown =) Because it's so easy to do a `Column > Markdown > Table > Markdown`.

I'll probably use this widget a lot in some projects I'm working. If this is the case, I'll try to help with PR instead of just issues.
