### ISSUE TITLE
Dart 3 Null Safety Fix on CopyButton

### ISSUE THREAD

**Issue by cliftonlabrum** [chenzhiguang/markdown_viewer#83]
There's a small adjustment needed in this package to make it compatible with Dart 3's null safety.

> .../pub.dev/markdown_viewer-0.5.0/lib/src/widgets/copy_button.dart(49,55): error GC2F972A8: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't. 

https://github.com/tagnote-app/markdown_viewer/blob/master/lib/src/widgets/copy_button.dart

Thanks! 😄

**Comment by chenzhiguang** [comment]
@cliftonlabrum Thank you for reporting. I've made a quick fix for now, please try `markdown_viewer: ^0.6.1`. This fix may not be ideal, it should work. I apologize for not maintaining and upgrading this package for a while, but I will catch up soon.

**Comment by cliftonlabrum** [comment]
Thank you!
