### ISSUE TITLE
Line breaks not honoured

### ISSUE THREAD

**Issue by JCKodel** [chenzhiguang/markdown_viewer#88]
Consider this markdown:

```
Legenda:\n\n**H**: Hidratações\n**N**: Nutrições e umectações\n**R**: Reconstruções
```

The expected output would be:

---

Legenda:

**H**: Hidratações
**N**: Nutrições e umectações
**R**: Reconstruções

---

But markdown_viewer render it without the line breaks:

![image](https://github.com/tagnote-app/markdown_viewer/assets/379339/e9d42567-fd53-4a5d-ba1f-ce965676d481)

(BTW, double line breaks are NOT a solution, because they add a second line-break between the items:)
```
Legenda:

**H**: Hidratações

**N**: Nutrições e umectações

**R**: Reconstruções
```

**Comment by chenzhiguang** [comment]
This markdown_viewer follows the CommonMark specification. You have to type at least 2 spaces or add a `\` to the end of a line in order to produce a hard break:
https://spec.commonmark.org/0.30/#hard-line-breaks

**Comment by JCKodel** [comment]
Ok.

It was confusing because GitHub markdown doesn't work that way. Maybe some documentation about hard breaks? =)

**Comment by chenzhiguang** [comment]
Maybe I should render the softbreak as a line break too. I will enable this feature by default.

BTW, I am busy at another project at this moment, I was working on a Notes app, this is the reason why I created this Markdown thing, but this Notes project has been paused.

**Comment by JCKodel** [comment]
> BTW, I am busy at another project at this moment...

That's on you. You made a better markdown widget than Google official one, so, suffer the consequences >=)
